from typing import Any, List, Optional, Protocol, Dict, runtime_checkable
from enum import Enum

class NodeStatus(Enum):
    PENDING = "pending"
    RESUMING = "resuming"
    RUNNING = "running"
    CANCELING = "canceling"
    CANCELED = "canceled"
    COMPLETED = "completed"
    FAILED = "failed"

@runtime_checkable
class INodeContext(Protocol):
    """节点执行上下文接口"""
    @property
    def node_id(self) -> str: ...
    @property
    def context_id(self) -> str: ...
    def is_cancelled(self) -> bool: ...
    def report_progress(self, current: int, total: Optional[int], metadata: Optional[Dict] = None) -> None: ...
    def report_usage(self, metrics: Dict[str, Any]) -> None: ...
    def log(self, message: str, level: str = "info") -> None: ...
    def report_failed_items(self, items: List[Any], error: Exception) -> None: ...

@runtime_checkable
class INode(Protocol):
    """最基础的节点接口：仅负责生命周期与 I/O"""
    @property
    def node_id(self) -> str: ...
    @property
    def status(self) -> NodeStatus: ...
    
    def bind_io(self, input_stream: Any, output_stream: Any) -> None: ...
    def open(self, ctx: Optional[Any] = None, progress: Optional[Any] = None) -> None: ...
    def run(self) -> None: ...
    def close(self) -> None: ...
    def cancel(self) -> None: ...

@runtime_checkable
class IBatchNode(INode, Protocol):
    """具有批处理能力的节点接口"""
    def process_batch(self, data: List[Any]) -> List[Any]:
        """
        核心处理逻辑：由引擎调用
        """
        ...

@runtime_checkable
class IRecoverableNode(INode, Protocol):
    """可恢复节点接口"""
    def get_runtime(self) -> Dict[str, Any]: ...
    def resume_from_runtime(self, runtime_data: Dict[str, Any]) -> None: ...
